[workspace]
authors = ["bev-gorry <beverley_g@hotmail.com>"]
channels = ["conda-forge", "nvidia/label/cuda-12.0.0"]
name = "multi-session-sfm"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[environments]
default = { features = ["pipeline"], no-default-feature = true }
vslamlab = { features = ["pipeline", "vslamlab"], no-default-feature = true }
vprlab = { features = ["pipeline", "vprlab"], no-default-feature = true }
lightglue = { features = ["pipeline", "lightglue"], no-default-feature = true }
rerun-viewer = { features = ["rerun-viewer"], no-default-feature = true }

##### Full pipeline #####
[feature.pipeline]
platforms = ["linux-64"]

[feature.pipeline.tasks]
submodule-update.cmd = "git submodule update --init --recursive"
train-splatfacto.cmd = "python -m scripts.train_nerfstudio {{ args }}"
train-splatfacto.args = [
  { "arg" = "args", "default" = "--exp_yaml=arguments/exp_test.yaml" },
]

[feature.pipeline.dependencies]
python = "*"
opencv = "*"
matplotlib = "*"
pyyaml = "*"
pandas = "*"
seaborn = "*"
tqdm = "*"
pytorch-gpu = "*"
torchvision = ">=0.3"
huggingface_hub = ">=1.18.0,<2"
open3d = ">=0.19.0"

[feature.pipeline.system-requirements]
cuda = "12.0"

##### VSLAM-LAB #####
[feature.vslamlab]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[feature.vslamlab.tasks]
submodule-update.cmd = "git submodule update --init --recursive baselines/VSLAM_LAB"
vslamlab.cmd = "python vslamlab_gui.py vslamlab {{ exp_yaml }} {{ overwrite }}"
vslamlab.cwd = "baselines/VSLAM_LAB"
vslamlab.args = [
  { "arg" = "exp_yaml", "default" = "../../arguments/exp_test_vslamlab.yaml" },
  { "arg" = "overwrite", "default" = " " },
]

[feature.vslamlab.dependencies]
python = "3.13.*"
pyyaml = "*"
matplotlib = "*"
pandas = "*"
py-opencv = "*"
scipy = "*"
requests = "*"
inputimeout = "*"
scikit-learn = "*"
tqdm = "*"
google-api-python-client = "*"
google-auth-oauthlib = "*"
huggingface_hub = "*"
py7zr = "*"
exifread = "*"
pyproj = "*"
nvidia-ml-py = "*"
evo = "*"
git-lfs = "*"
piexif = "*"
psutil = "*"
loguru = "*"
utm = "*"
7zip = "*"
viser = "*"
open3d = "*"
gdown = "*"


##### VPR-LAB #####
[feature.vprlab]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[feature.vprlab.tasks]
submodule-update-vpr-methods.cmd = "git submodule update --init --recursive baselines/VPR-methods-evaluation"
vpr-lab.cmd = "python vpr-lab.py --method={{ method }} --exp_yaml={{ exp_yaml }} --rot_360"
vpr-lab.cwd = "baselines/VPR-methods-evaluation"
vpr-lab.args = [
  { "arg" = "method", "default" = "megaloc" },
  { "arg" = "exp_yaml", "default" = "../../arguments/exp_test.yaml" },
]

[feature.vprlab.dependencies]
python="3.11.*"
faiss-cpu = "=1.8.0"
gdown = ">=6.1.0,<7"
scikit-image = "*"
scikit-learn = ">=1.9.0,<2"
huggingface_hub = "*"
safetensors = ">=0.8.0,<0.9"
loguru = ">=0.7.3,<0.8"
numpy = ">=1.26.4,<2"
pillow = ">=12.2.0,<13"
scipy = ">=1.17.1,<2"
tqdm = ">=4.68.2,<5"

##### LightGlue #####
[feature.lightglue]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[feature.lightglue.tasks]
submodule-update-lightglue.cmd = "git submodule update --init --recursive baselines/LightGlue"
install = {cmd = "python -m pip install -e .", cwd = "baselines/LightGlue", depends-on = ["submodule-update-lightglue"]}
rerun-viewer.cmd = "python -m vis.rerun_viewer {{ args }}"
rerun-viewer.args = [
  { "arg" = "args", "default" = "--exp_yaml=arguments/exp_test.yaml" },
]
export-session-splats.cmd = "python -m vis.export_session_splats {{ args }}"
export-session-splats.args = [
  { "arg" = "args", "default" = "--exp_yaml=arguments/exp_test.yaml" },
]

[feature.lightglue.dependencies]
python = "*"
opencv = "*"
matplotlib = "*"
pyyaml = "*"
pandas = "*"
seaborn = "*"
tqdm = "*"
pytorch-gpu = "*"
torchvision = ">=0.3"
kornia = ">=0.6.11"
open3d = ">=0.19.0"
transforms3d = ">=0.4.2,<0.5"
rerun-sdk = ">=0.33,<0.34"
pip = "*"

##### Rerun Viewer #####
[feature.rerun-viewer]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[feature.rerun-viewer.tasks]
rerun-viewer.cmd = "python -m vis.rerun_viewer {{ args }}"
rerun-viewer.args = [
  { "arg" = "args", "default" = "--exp_yaml=arguments/exp_test.yaml" },
]

[feature.rerun-viewer.dependencies]
python = ">=3.11,<3.13"
numpy = "*"
pandas = "*"
py-opencv = "*"
pyyaml = "*"
rerun-sdk = ">=0.33,<0.34"
tqdm = "*"
